config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  get '/register', to: 'users#new'
  post '/users', to: 'users#create'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  # get '/logout', to: 'sessions#logout_user' # using get AND destroy here since I want 'Log out' to be a link, and link defaults to a get. But, I also don't want the DELETE '/login' path to be used for anything else.
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
  end

  post '/search', to: 'congress#search'
  post '/search_state', to: 'congress#search_state'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: true, presence: true
  
    has_secure_password

    enum role: ['default','admin']
  end

app/controllers/admin/base_controller.rb
class Admin::BaseController <ApplicationController
    before_action :require_admin

    private 
    def require_admin 
        render file: '/public/404' if current_user && !current_user.admin?
    end 
end 

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController <Admin::BaseController
    def index 
    end 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user 
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end 

end

app/controllers/congress_controller.rb
class CongressController < ApplicationController
  def search
    @found_senator = CongressFacade.find_senator_by_last_name(params[:search])
  end

  def search_state
    @state = params[:state]
    @house_members = CongressFacade.find_all_house_members_by_state(params[:state])
  end
end

app/controllers/propublica_controller.rb
class PropublicaController < ApplicationController

  def search
    member_search = params[:search]
    conn = Faraday.new(url: "https://api.propublica.org") do |faraday|
      faraday.headers["X-API-KEY"] = ENV['GOVT_API']
    end
    response = conn.get('/congress/v1/116/senate/members.json')

    json = JSON.parse(reponse.body, symbolize_names: true)
    @members = json[:results][0][:members]

    found_member = @members.find {|m| m[:last_name] == member_search}
    binding.pry
  end
end  

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:message] = "Welcome #{user.email}!"

      if user.regular?
        redirect_to root_path
      elsif user.admin?
        redirect_to admin_dashboard_path
      end

    else
      flash[:message] = "email or password is incorrect"
      render :new
    end
  end

  def destroy
    session.delete :user_id
    # or use session.clear to erase all session data
    flash[:message] = "You have been logged out"
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
    def new 
    end 

    def create
        found_user = User.find_by(username: params[:username])
        if found_user && found_user.authenticate(params[:password])
            session[:user_id] = found_user.id
            flash[:success] = "Welcome, #{found_user.username}!"
            redirect_to root_path if current_user.default?
            redirect_to admin_dashboard_path if current_user.admin?
        else 
            flash[:error] = "Your username or password are incorrect"
            redirect_to "/login"
        end 
    end 

    def destroy
        session[:user_id] = nil
        redirect_to '/'
    end 
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end 

    def create
        user = user_params
        user[:username] = user[:username].downcase
        new_user = User.create(user)
        if new_user.save
            session[:user_id] = new_user.id
            flash[:success] = "Welcome, #{new_user.username}!"
        end 
        redirect_to root_path
    end

    private 

    def user_params 
        params.require(:user).permit(:username, :password)
    end 
end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
    def index 
    end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/states_helper.rb
module StatesHelper
    def us_states
      [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
      ]
    end
  end
  

app/views/admin/dashboard/index.html.erb
<h1>Admin Dashboard</h1>

app/views/congress/search.html.erb
<h1>Senator <%= @found_senator.first_name %> <%= @found_senator.last_name %></h1>
<p>Twitter Handle: <%= @found_senator.twitter_account %></p>

app/views/congress/search_state.html.erb
<% if @house_members %>
  <h1><%=@house_members.size%> Results </h1>
  <% cache "house-member-#{@state}", expires_in: 10.seconds do %>
    <% @house_members.each do |house_member| %>
      <ul class="house_members">
        <li class="name"><%= house_member.name%></li>
        <li class="district"><%= house_member.district%></li>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CongressTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/session/new.html.erb
<%= form_with url: login_path, method: :post, local: true do |f| %>
  <%= f.label :email, "Email: " %>
  <%= f.text_field :email %>
  <%= f.label :password, "Password: " %>
  <%= f.password_field :password %>
  <%= f.submit "Log In" %>
<% end %>

app/views/users/login_form.html.erb
<%= form_with url: login_path, method: :post do |form| %>
  <%= form.label :username, 'Username:' %>
  <%= form.text_field :username %>
  <%= form.label :password, 'Password:' %>
  <%= form.password_field :password %>
  <%= form.submit 'Log In' %>
<% end %>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |form| %>
  <%= form.label :username, 'Username:' %>
  <%= form.text_field :username %>
  <%= form.label :password, 'Password:' %>
  <%= form.password_field :password %>
  <%= form.submit 'Create User' %>
<% end %>

app/views/users/show.html.erb
<h1>Hello, <%= current_user.email %>!</h1>

app/views/welcome/index.html.erb
<h1>WELCOME!</h1>

<% if current_user %>
    <%= link_to "Log out", '/logout', method: :delete %>
<% else %>
    <%= link_to "Register as a User", "/register" %>
    <%= link_to "I already have an account", "/login" %>
<% end %>

<%= form_with url: search_path, method: :post, local: true do |form|  %>
  <%= form.label 'Search for Senate Members' %>
  <%= form.text_field :search %>
  <%= form.submit 'Search' %>
<% end %>

<%= form_with url: search_state_path, local: true do |form| %>
  <%= form.label :search_state, 'Search For House Members Of A Specific State' %>
  <%= form.select :state, us_states %>
  <%= form.submit 'Search By State' %>
<% end %>